Guestbook.Web/Controllers/MessagesController.cs
using DataAccess.Data;
using DataAccess.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Dynamic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace Guestbook.Web.Controllers
{
    [Authorize]
    public class MessagesController : Controller
    {
        private readonly IMessageData _messageData;
        private readonly IReplyData _replyData;

        public MessagesController(IMessageData messageData, IReplyData replyData)
        {
            _messageData = messageData;
            _replyData = replyData;
        }

        public async Task<IActionResult> Edit(int MessageId, int UserId)
        {
            var currentUser = this.User;
            var currentUserId = Int32.Parse(currentUser.FindFirst(ClaimTypes.NameIdentifier).Value);
            if (currentUserId != UserId) return Unauthorized();

            var message = await _messageData.GetMessage(MessageId);
            return View(message);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(MessageModel input)
        {
            var currentUser = this.User;
            var currentUserId = Int32.Parse(currentUser.FindFirst(ClaimTypes.NameIdentifier).Value);
            if (currentUserId != input.User.UserId) return Unauthorized();

            await _messageData.UpdateMessage(input);
            return LocalRedirect("/");
        }

        [HttpPost]
        public async Task<IActionResult> Create(string Content)
        {
            var currentUser = this.User;
            var userId = Int32.Parse(currentUser.FindFirst(ClaimTypes.NameIdentifier).Value);
            await _messageData.InsertMessage(Content, userId);
            return LocalRedirect("/");
        }

        public async Task<IActionResult> Show(int MessageId)
        {
            var message = await _messageData.GetMessageWithUser(MessageId);
            var replies = await _replyData.GetReplies(MessageId);
            dynamic mymodel = new ExpandoObject();
            mymodel.Message = message;
            mymodel.Replies = replies;
            return View(mymodel);
        }

        public async Task<IActionResult> Delete(int MessageId, int UserId)
        {
            var currentUser = this.User;
            var currentUserId = Int32.Parse(currentUser.FindFirst(ClaimTypes.NameIdentifier).Value);
            if (currentUserId != UserId) return Unauthorized();

            await _messageData.DeleteMessage(MessageId);
            return LocalRedirect("/");
        }
    }
}

Guestbook.Web/Controllers/RepliesController.cs
using DataAccess.Data;
using Guestbook.Web.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace Guestbook.Web.Controllers
{
    [Authorize]
    public class RepliesController : Controller
    {
        private readonly IReplyData _replyData;

        public RepliesController(IReplyData replyData)
        {
            _replyData = replyData;
        }

        public IActionResult Create(int MessageId)
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(ReplyInputModel input)
        {
            var currentUser = this.User;
            var currentUserId = Int32.Parse(currentUser.FindFirst(ClaimTypes.NameIdentifier).Value);
            await _replyData.InsertReply(input.Content, input.MessageId, currentUserId);

            return RedirectToAction("Show", "Messages", 
                new { MessageId = input.MessageId });
        }

        public async Task<IActionResult> Delete(int ReplyId, int UserId, int MessageId)
        {
            var currentUser = this.User;
            var currentUserId = Int32.Parse(currentUser.FindFirst(ClaimTypes.NameIdentifier).Value);
            if (currentUserId != UserId) return Unauthorized();

            await _replyData.DeleteReply(ReplyId);
            return RedirectToAction("Show", "Messages", new { MessageId });
        }
    }
}

Guestbook.Web/Views/Messages/Edit.cshtml
@model MessageModel

<div class="edit-message-page">
    <div class="page-header">
        <h1>Editing message</h1>
    </div>

    <div class="row">
        <div class="col-sm-6">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">Update your message with new content</h3>
                </div>
                <div class="panel-body">

                    <form asp-route="Edit">
                        <input type="hidden" asp-for="MessageId" />
                        <input type="hidden" asp-for="User.UserId" />

                        <fieldset>
                            <div class="form-group">
                                <textarea class="form-control" placeholder="Write your new message" asp-for="Content" autofocus></textarea>
                            </div>
                            <div class="form-group">
                                <button class="btn btn-primary">Update</button>
                            </div>
                        </fieldset>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

Guestbook.Web/Views/Messages/Show.cshtml
@model dynamic

<div>
    <h1 class="font-weight-normal">Author: @Model.Message.User.FirstName @Model.Message.User.LastName</h1>
    <address class="mb-2">
        Email Address: <a href="mailto:@Model.Message.User.Email">
            <span class="font-weight-bold">@Model.Message.User.Email</span>
        </a>
    </address>
</div>

<div class="pt-4">
    <blockquote class="blockquote">
        <p class="mb-2 lead" style="font-size: 2rem">@Model.Message.Content</p>
        <footer class="blockquote-footer">Message created at <cite>@Model.Message.CreatedAt.ToString("MMMM dd, yyyy")</cite></footer>
    </blockquote>
</div>

<h2 class="pb-2 pt-3">Replies</h2>
<div class="pb-3">
    <a asp-controller="Replies"
       asp-action="Create"
       asp-route-MessageId="@Model.Message.MessageId"
       class="btn btn-primary">Add a reply</a>
</div>
@if (Model.Replies.Count == 0)
{
    <p>There are not replies under this message.</p>
}
else
{
    foreach (var reply in Model.Replies)
    {
        <div class="card mb-1 border-bottom-0 border-right-0 border-left-0">
            <div class="card-body">
                <h5 class="card-title">@reply.User.FirstName @reply.User.LastName</h5>
                <h6 class="card-subtitle mb-2 text-muted">
                    @reply.User.Email
                </h6>
                <p class="card-text" style="font-size: 1.5em">@reply.Content</p>
                <p class="card-text"><small class="text-muted">@reply.CreatedAt.ToString("MMMM dd, yyyy")</small></p>
                @if (User.FindFirst(System.Security.Claims.ClaimTypes.NameIdentifier).Value == reply.User.UserId.ToString())
                {
                    <a asp-controller="Replies"
                       asp-action="Delete"
                       asp-route-ReplyId="@reply.ReplyId"
                       asp-route-UserId="@reply.User.UserId"
                       asp-route-MessageId="@Model.Message.MessageId"
                       class="btn btn-danger">
                        Delete
                    </a>
                }
            </div>
        </div>
    }
}