Guestbook.Web/Controllers/HomeController.cs
using DataAccess.Data;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace Guestbook.Web.Controllers
{
    [Authorize]
    public class HomeController : Controller
    {
        private readonly IMessageData _messageData;

        public HomeController(IMessageData messageData)
        {
            _messageData = messageData;
        }

        public async Task<IActionResult> Index()
        {
            var messages = await _messageData.GetTop15Messages();
            return View(messages);
        }

        public IActionResult Privacy()
        {
            return View();
        }
    }
}

Guestbook.Web/Controllers/MessagesController.cs
using DataAccess.Data;
using DataAccess.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Dynamic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace Guestbook.Web.Controllers
{
    [Authorize]
    public class MessagesController : Controller
    {
        private readonly IMessageData _messageData;
        private readonly IReplyData _replyData;

        public MessagesController(IMessageData messageData, IReplyData replyData)
        {
            _messageData = messageData;
            _replyData = replyData;
        }

        public async Task<IActionResult> Edit(int MessageId, int UserId)
        {
            var currentUser = this.User;
            var currentUserId = Int32.Parse(currentUser.FindFirst(ClaimTypes.NameIdentifier).Value);
            if (currentUserId != UserId) return Unauthorized();

            var message = await _messageData.GetMessage(MessageId);
            return View(message);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(MessageModel input)
        {
            var currentUser = this.User;
            var currentUserId = Int32.Parse(currentUser.FindFirst(ClaimTypes.NameIdentifier).Value);
            if (currentUserId != input.User.UserId) return Unauthorized();

            await _messageData.UpdateMessage(input);
            return LocalRedirect("/");
        }

        [HttpPost]
        public async Task<IActionResult> Create(string Content)
        {
            var currentUser = this.User;
            var userId = Int32.Parse(currentUser.FindFirst(ClaimTypes.NameIdentifier).Value);
            await _messageData.InsertMessage(Content, userId);
            return LocalRedirect("/");
        }

        public async Task<IActionResult> Show(int MessageId)
        {
            var message = await _messageData.GetMessageWithUser(MessageId);
            var replies = await _replyData.GetReplies(MessageId);
            dynamic mymodel = new ExpandoObject();
            mymodel.Message = message;
            mymodel.Replies = replies;
            return View(mymodel);
        }

        public async Task<IActionResult> Delete(int MessageId, int UserId)
        {
            var currentUser = this.User;
            var currentUserId = Int32.Parse(currentUser.FindFirst(ClaimTypes.NameIdentifier).Value);
            if (currentUserId != UserId) return Unauthorized();

            await _messageData.DeleteMessage(MessageId);
            return LocalRedirect("/");
        }
    }
}

Guestbook.Web/Views/Home/Index.cshtml
@model IEnumerable<MessageModel>
@{
    ViewData["Title"] = "Home Page";
}

<div class="row">
    <div class="col-7">
        <div>
            <h1 class="display-4">Recent Messages</h1>
        </div>
        <br />

        @if (!Model.Any())
        {
            <p>There are no messages.</p>
        }
        else
        {

            @foreach (var message in Model)
            {
                <div class="card mb-3">
                    <div class="card-body">
                        <h5 class="card-title">
                            @message.User.FirstName @message.User.LastName -
                            <span class="small">
                                <time datetime="@message.CreatedAt">@message.CreatedAt.ToString("MMMM dd, yyyy")</time>
                            </span>
                        </h5>
                        <h6 class="card-subtitle mb-2 text-muted">
                            @message.User.Email
                        </h6>
                        <p class="card-text">@message.Content</p>
                        <a asp-controller="Messages"
                           asp-action="Show"
                           asp-route-MessageId="@message.MessageId"
                           class="btn btn-outline-dark">
                            Show Replies
                        </a>
                        @if (User.FindFirst(System.Security.Claims.ClaimTypes.NameIdentifier).Value == message.User.UserId.ToString())
                        {
                            <a asp-controller="Messages"
                               asp-action="Edit"
                               asp-route-MessageId="@message.MessageId"
                               asp-route-UserId="@message.User.UserId"
                               class="btn btn-primary">
                                Edit
                            </a>
                            <a asp-controller="Messages"
                               asp-action="Delete"
                               asp-route-MessageId="@message.MessageId"
                               asp-route-UserId="@message.User.UserId"
                               class="btn btn-danger">
                                Delete
                            </a>
                        }
                    </div>
                </div>
            }
        }
    </div>
    <div class="col-5">
        @if (User.Identity.IsAuthenticated)
        {
            <form method="post" class="sticky-top" style="padding-top: 20px" asp-controller="Messages" asp-action="Create">
                <fieldset>
                    <div class="form-group">
                        <textarea name="Content" rows="5" placeholder="Write a message..." class="form-control"></textarea>
                    </div>
                    <div class="text-right form-group">
                        <button type="submit" class="btn btn-primary ">Submit</button>
                    </div>
                </fieldset>
            </form>
        }
    </div>
</div>